[package]
name = "x86"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field.workspace = true
bitflags.workspace = true
anyhow.workspace = true
snafu.workspace = true
